config/routes.rb
Rails.application.routes.draw do

  resources :vk_enderecoanuncios
  resources :vk_enderecoempresas
  resources :vk_anunciofavoritos
  resources :vk_anuncios do
    member do
      get  :endereco
      get  :show_produto
    end
  end
  resources :vk_empresavitrines
  resources :vk_vitrines
  resources :vk_produtos
  resources :vk_empresas
  resources :vk_enderecos
  resources :vk_categoriaprodutos
  devise_for :users
  resources :vk_cidades
  resources :vk_estados

  root  'site#home'

  match '/listarCidade', to: 'vk_cidades#get_cities', via: 'get'
  match '/buscaVitrines', to: 'vk_vitrines#buscaVitrines', via: 'get'

  get '/anuncioshow/:id', to: 'site#show_anuncio', as: 'anuncioshow'
  get '/olhekpesquisa', to: 'site#index', as: 'olhekpesquisa'

  match '/buscaProdutos', to: 'vk_produtos#busca_produtos', via: 'get'

  match '/olheksalvarFavorito', to: 'vk_anunciofavoritos#salvar', via: 'get'
  match '/recomendar', to: 'vk_anuncios#recomendar', via: 'get'

  match '/olheksalvaEndereco', to: 'vk_empresas#salva_endereco', via: 'get'
  match '/olhekexcluiEndereco', to: 'vk_empresas#exclui_endereco', via: 'get'

  match '/listaProdutos', to: 'vk_anuncios#produtos', via: 'get'

  get '/anunciar/:produto_id', to: 'vk_anuncios#new', as: 'anunciar'
  get '/buscaEnderecoEmpresa', to: 'vk_anuncios#busca_endereco_empresa', as: 'buscaEnderecoEmpresa'
  get '/buscaEnderecoAnuncio', to: 'vk_anuncios#busca_endereco_anuncio', as: 'buscaEnderecoAnuncio'
  get '/salvaEnderecoAnuncio', to: 'vk_anuncios#salva_endereco_anuncio', as: 'salvaEnderecoAnuncio'
  get '/excluiEnderecoAnuncio', to: 'vk_anuncios#exclui_endereco_anuncio', as: 'excluiEnderecoAnuncio'
  get '/:id', to: 'site#show_empresa', as: 'loja'










end

app/models/vk_empresavitrine.rb
class VkEmpresavitrine < ActiveRecord::Base
  belongs_to :vk_vitrine
  belongs_to :vk_empresa
end

app/controllers/vk_empresavitrines_controller.rb
class VkEmpresavitrinesController < ApplicationController
  before_action :set_vk_empresavitrine, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vk_empresavitrines = VkEmpresavitrine.all
    respond_with(@vk_empresavitrines)
  end

  def show
    respond_with(@vk_empresavitrine)
  end

  def new
    @vk_empresavitrine = VkEmpresavitrine.new
    respond_with(@vk_empresavitrine)
  end

  def edit
  end

  def create
    @vk_empresavitrine = VkEmpresavitrine.new(vk_empresavitrine_params)
    @vk_empresavitrine.save
    respond_with(@vk_empresavitrine)
  end

  def update
    @vk_empresavitrine.update(vk_empresavitrine_params)
    respond_with(@vk_empresavitrine)
  end

  def destroy
    @vk_empresavitrine.destroy
    respond_with(@vk_empresavitrine)
  end

  private
    def set_vk_empresavitrine
      @vk_empresavitrine = VkEmpresavitrine.find(params[:id])
    end

    def vk_empresavitrine_params
      params.require(:vk_empresavitrine).permit(:vk_vitrine_id, :vk_empresa_id)
    end
end

app/helpers/vk_empresavitrines_helper.rb
module VkEmpresavitrinesHelper
end

app/views/vk_empresavitrines/_form.html.erb
<%= form_for(@vk_empresavitrine) do |f| %>
  <% if @vk_empresavitrine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vk_empresavitrine.errors.count, "error") %> prohibited this vk_empresavitrine from being saved:</h2>

      <ul>
      <% @vk_empresavitrine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vk_vitrine_id %><br>
    <%= f.text_field :vk_vitrine_id %>
  </div>
  <div class="field">
    <%= f.label :vk_empresa_id %><br>
    <%= f.text_field :vk_empresa_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vk_empresavitrines/edit.html.erb
<h1>Editing vk_empresavitrine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vk_empresavitrine %> |
<%= link_to 'Back', vk_empresavitrines_path %>

app/views/vk_empresavitrines/index.html.erb
<h1>Listing vk_empresavitrines</h1>

<table>
  <thead>
    <tr>
      <th>Vk vitrine</th>
      <th>Vk empresa</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vk_empresavitrines.each do |vk_empresavitrine| %>
      <tr>
        <td><%= vk_empresavitrine.vk_vitrine %></td>
        <td><%= vk_empresavitrine.vk_empresa %></td>
        <td><%= link_to 'Show', vk_empresavitrine %></td>
        <td><%= link_to 'Edit', edit_vk_empresavitrine_path(vk_empresavitrine) %></td>
        <td><%= link_to 'Destroy', vk_empresavitrine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vk empresavitrine', new_vk_empresavitrine_path %>

app/views/vk_empresavitrines/new.html.erb
<h1>New vk_empresavitrine</h1>

<%= render 'form' %>

<%= link_to 'Back', vk_empresavitrines_path %>

app/views/vk_empresavitrines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vk vitrine:</strong>
  <%= @vk_empresavitrine.vk_vitrine %>
</p>

<p>
  <strong>Vk empresa:</strong>
  <%= @vk_empresavitrine.vk_empresa %>
</p>

<%= link_to 'Edit', edit_vk_empresavitrine_path(@vk_empresavitrine) %> |
<%= link_to 'Back', vk_empresavitrines_path %>