config/routes.rb
Rails.application.routes.draw do

  resources :vk_enderecoanuncios
  resources :vk_enderecoempresas
  resources :vk_anunciofavoritos
  resources :vk_anuncios do
    member do
      get  :endereco
      get  :show_produto
    end
  end
  resources :vk_empresavitrines
  resources :vk_vitrines
  resources :vk_produtos
  resources :vk_empresas
  resources :vk_enderecos
  resources :vk_categoriaprodutos
  devise_for :users
  resources :vk_cidades
  resources :vk_estados

  root  'site#home'

  match '/listarCidade', to: 'vk_cidades#get_cities', via: 'get'
  match '/buscaVitrines', to: 'vk_vitrines#buscaVitrines', via: 'get'

  get '/anuncioshow/:id', to: 'site#show_anuncio', as: 'anuncioshow'
  get '/olhekpesquisa', to: 'site#index', as: 'olhekpesquisa'

  match '/buscaProdutos', to: 'vk_produtos#busca_produtos', via: 'get'

  match '/olheksalvarFavorito', to: 'vk_anunciofavoritos#salvar', via: 'get'
  match '/recomendar', to: 'vk_anuncios#recomendar', via: 'get'

  match '/olheksalvaEndereco', to: 'vk_empresas#salva_endereco', via: 'get'
  match '/olhekexcluiEndereco', to: 'vk_empresas#exclui_endereco', via: 'get'

  match '/listaProdutos', to: 'vk_anuncios#produtos', via: 'get'

  get '/anunciar/:produto_id', to: 'vk_anuncios#new', as: 'anunciar'
  get '/buscaEnderecoEmpresa', to: 'vk_anuncios#busca_endereco_empresa', as: 'buscaEnderecoEmpresa'
  get '/buscaEnderecoAnuncio', to: 'vk_anuncios#busca_endereco_anuncio', as: 'buscaEnderecoAnuncio'
  get '/salvaEnderecoAnuncio', to: 'vk_anuncios#salva_endereco_anuncio', as: 'salvaEnderecoAnuncio'
  get '/excluiEnderecoAnuncio', to: 'vk_anuncios#exclui_endereco_anuncio', as: 'excluiEnderecoAnuncio'
  get '/:id', to: 'site#show_empresa', as: 'loja'










end

app/models/vk_anuncio.rb
class VkAnuncio < ActiveRecord::Base
  belongs_to :vk_produto
  belongs_to :vk_empresa
  belongs_to :user
  belongs_to :inclusao, :class_name => "User", :foreign_key => "user_inclusao"


  def favorito
      @favorito
  end

  def favorito=(val)
    @favorito = val
  end


  def self.find_by_nome_anuncio_or_all(query)
    if query
      query = query.downcase
     self.where('lower(desc_titulo)like ?',"%#{query}%")

    else
     self.all
    end
  end


  def self.cria_funcao
    query = " CREATE OR REPLACE FUNCTION distancia_km(lat1 NUMERIC, lng1 NUMERIC, lat2 NUMERIC, lng2 NUMERIC) "
    query = query +  " RETURNS DOUBLE PRECISION AS "
    query = query +  " $BODY$ "
    query = query +  " SELECT 6371 * acos( "
    query = query +  " sin( radians($1) ) * sin( radians( $3 )) "
    query = query +  " + cos( radians($1) ) * cos( radians( $3 )) * cos(radians($4) - radians($2))  ) "
    query = query +  " as distance; "
    query = query +  " $BODY$ "
    query = query +  " LANGUAGE sql IMMUTABLE COST 100; "
    results = ActiveRecord::Base.connection.execute(query);
  end

 def self.busca_nome_vitrine(nome,vitrine)
   data = Time.now
    if nome
      nome = nome.downcase
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id INNER JOIN vk_empresavitrines ev on ve.id = ev.vk_empresa_id INNER JOIN vk_produtos pr on vk_produto_id = pr.id').where('ev.vk_vitrine_id = ? and data_inicio < ? and data_fim  > ? and lower(pr.nome_produto) like ?',vitrine,data,data,"%#{nome}%")
     else
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id INNER JOIN vk_empresavitrines ev on ve.id = ev.vk_empresa_id ').where('ev.vk_vitrine_id = ?',vitrine)
    end
 end

 def self.busca_categoria_vitrine(produto,vitrine)
   data = Time.now
    if produto
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id INNER JOIN vk_empresavitrines ev on ve.id = ev.vk_empresa_id INNER JOIN vk_produtos pr on vk_produto_id = pr.id INNER JOIN vk_categoriaprodutos cp on pr.vk_categoriaproduto_id = cp.id').where('ev.vk_vitrine_id = ? and data_inicio <= ? and data_fim  >= ? and cp.id = ?',vitrine,data,data,produto)
     else
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id INNER JOIN vk_empresavitrines ev on ve.id = ev.vk_empresa_id ').where('ev.vk_vitrine_id = ?',vitrine)
    end
 end

 def self.busca_por_vitrine(vitrine)
       data = Time.now
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id INNER JOIN vk_empresavitrines ev on ve.id = ev.vk_empresa_id ').where('ev.vk_vitrine_id = ? and data_inicio < ? and data_fim  > ?',vitrine,data,data).paginate(:page => params[:page], :per_page => 10)
  end

  def self.busca_lat_long(lat,long)
    self.cria_funcao
    data = Time.now

    sql = " INNER JOIN vk_enderecoanuncios ena on ena.vk_anuncio_id = vk_anuncios.id INNER JOIN vk_enderecos en on ena.vk_endereco_id = en.id "
    sql = sql + " WHERE data_inicio <= '#{data}' AND data_fim >= '#{data}' "
    sql = sql + " AND distancia_km(#{lat}, #{long}, CAST(en.latitude as NUMERIC), CAST(en.longitude AS NUMERIC)) <= 10 "
    sql = sql + " AND distancia_km(#{lat}, #{long}, CAST(en.latitude as NUMERIC), CAST(en.longitude AS NUMERIC)) > 0"
    self.joins(sql)

  end

  def self.busca_por_empresa(query)
    query = query.downcase
      self.joins('INNER JOIN vk_empresas ve on ve.id = vk_empresa_id').where('lower(ve.nome_pagina) = ?',"#{query}")
  end


end

app/controllers/vk_anuncios_controller.rb
class VkAnunciosController < ApplicationController
  before_action :set_vk_anuncio, only: [:show, :edit, :update, :destroy]

  #before_action :authenticate_user!

  respond_to :html


def recomendar
  @vk_anuncio = VkAnuncio.find(params[:vk_anuncio_id])
  if @vk_anuncio.numr_recomendado == nil
     @vk_anuncio.numr_recomendado = 0
  end
  @vk_anuncio.numr_recomendado = @vk_anuncio.numr_recomendado + 1
  @vk_anuncio.save

  anuncio = VkAnuncio.where(id: params[:vk_anuncio_id])
  anuncio_json = anuncio.map{|item|{:id => item.id,
                                    :numr_recomendado => item.numr_recomendado}}
  render :json => anuncio_json

end

def show_produto
  @vk_produto = VkProduto.find(params[:id])
end
def busca_endereco_anuncio
  retorna_endereco_anuncio(params[:vk_anuncio_id])
end

def retorna_endereco_anuncio(vk_anuncio)
   enderecoAnuncio = VkEnderecoanuncio.where(vk_anuncio_id: vk_anuncio)
   enderecoAnuncio_json = enderecoAnuncio.map { |item| {:id => item.id,
                                                       :nome_rua => item.vk_endereco.nome_rua,
                                                       :desc_quadra => item.vk_endereco.desc_quadra,
                                                       :desc_lote => item.vk_endereco.desc_lote,
                                                       :nome_bairro => item.vk_endereco.nome_bairro,
                                                       :desc_complemento => item.vk_endereco.desc_complemento,
                                                       :desc_cep => item.vk_endereco.desc_cep,
                                                       :nome_cidade => item.vk_endereco.vk_cidade.nome_cidade,
                                                       :sigl_estado => item.vk_endereco.vk_cidade.vk_estado.sigl_estado}}
 render :json => enderecoAnuncio_json
 end

def busca_endereco_empresa

  enderecoEmpresa = VkEnderecoempresa.where(vk_empresa_id: params[:vk_empresa_id])
  enderecoEmpresa_json = enderecoEmpresa.map { |item| {:id => item.id,
                                                       :vk_endereco_id => item.vk_endereco_id,
                                                       :nome_rua => item.vk_endereco.nome_rua,
                                                       :desc_quadra => item.vk_endereco.desc_quadra,
                                                       :desc_lote => item.vk_endereco.desc_lote,
                                                       :nome_bairro => item.vk_endereco.nome_bairro,
                                                       :desc_complemento => item.vk_endereco.desc_complemento,
                                                       :desc_cep => item.vk_endereco.desc_cep,
                                                       :nome_cidade => item.vk_endereco.vk_cidade.nome_cidade,
                                                       :sigl_estado => item.vk_endereco.vk_cidade.vk_estado.sigl_estado}}
  render :json => enderecoEmpresa_json
end

def salva_endereco_anuncio
 @vk_enderecoanuncio = VkEnderecoanuncio.new
 @vk_enderecoanuncio.vk_anuncio_id = params[:vk_anuncio_id]
 @vk_enderecoanuncio.vk_endereco_id = params[:vk_endereco_id]

 @vk_enderecoanuncio.save

 retorna_endereco_anuncio(params[:vk_anuncio_id])

end

def exclui_endereco_anuncio
 @vk_enderecoanuncio = VkEnderecoanuncio.find(params[:id])
 @vk_enderecoanuncio.destroy

 retorna_endereco_anuncio(params[:vk_anuncio_id])
end

 def produtos
   @vk_produtos = VkProduto.find_by_nome_produto_or_all(params[:q]).paginate(:page => params[:page], :per_page => 10)

   #@vk_produtos = VkProduto.exists?('nome_produto LIKE ?',"%#{params[:q]}%"])

   #Person.exists?(['name LIKE ?', "%#{query}%"])

   respond_with(@vk_produtos)
 end

  def index
   #@vk_anuncios = VkAnuncio.all
    @vk_anuncios = VkAnuncio.where(vk_empresa_id: current_user.id)
    respond_with(@vk_anuncios)
  end

  def show
    @vk_enderecoAnuncio = VkEnderecoanuncio.where(vk_anuncio_id: params[:id])
    respond_with(@vk_anuncio)
  end

  def new
    @vk_anuncio = VkAnuncio.new
    @vk_produto = VkProduto.find(params[:produto_id])
    @vk_anuncio.vk_produto_id = @vk_produto.id
    @nome_produto = @vk_produto.nome_produto

    respond_with(@vk_anuncio)
  end

  def edit

  end

  def endereco
    @vk_enderecoAnuncio = VkEnderecoanuncio.where(vk_anuncio_id: params[:id])
  end

  def create
    @vk_anuncio = VkAnuncio.new(vk_anuncio_params)

    @vk_anuncio.data_fim = (@vk_anuncio.data_fim + 23.hours + 59.minutes + 59.second)

    @vk_anuncio.save
    respond_with(@vk_anuncio)
  end

  def update
    @vk_anuncio.update(vk_anuncio_params)
    respond_with(@vk_anuncio)
  end

  def destroy
    @vk_anuncio.destroy
    respond_with(@vk_anuncio)
  end

  private
    def set_vk_anuncio
      @vk_anuncio = VkAnuncio.find(params[:id])
    end

    def vk_anuncio_params
      params.require(:vk_anuncio).permit(:desc_titulo, :desc_anuncio, :valr_produto, :valr_comdesconto, :data_inicio, :data_fim, :numr_qtddisponivel, :flag_ilimitado, :numr_visualizacao, :numr_click, :vk_produto_id, :vk_empresa_id, :user_inclusao, :numr_recomendado )
    end
end

app/helpers/vk_anuncios_helper.rb
module VkAnunciosHelper
end

app/views/vk_anuncios/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Novo anuncio</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

<%= render 'form' %>

  <%= link_to @vk_anuncio , :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-list-alt"></span> Exibir
  <% end %>

  <%= link_to vk_anuncios_path, :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>

app/views/vk_anuncios/endereco.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Endereços</h3>
  </div>


  <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     Infome para quais endereços esta promoção será valida.
  </div>

<button class="btn btn-success" type="button" onclick="$('#myModal1').modal('show');">Adicionar Endereços
   <span  class="glyphicon glyphicon-plus-sign"></span>
</button>
<hr>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Rua</th>
        <th>Quadra</th>
        <th>Lote</th>
        <th>Bairro</th>
        <th>Cep</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th></th>
      </tr>
    </thead>
    <tbody id="tlbendereco">
      <% @vk_enderecoAnuncio.each do |anuncio| %>
        <tr>
          <td><%= anuncio.vk_endereco.nome_rua %></td>
          <td><%= anuncio.vk_endereco.desc_quadra %></td>
          <td><%= anuncio.vk_endereco.desc_lote %></td>
          <td><%= anuncio.vk_endereco.nome_bairro %></td>
           <td><%= anuncio.vk_endereco.desc_cep %></td>
          <td><%= anuncio.vk_endereco.vk_cidade.nome_cidade %></td>
          <td><%= anuncio.vk_endereco.vk_cidade.vk_estado.sigl_estado %></td>
          <td align='right'>

          <button class="btn btn-default btn-sm" type="button" onclick="AcaoExcluir('<%=empresa.id%>');">
              <span  class="glyphicon glyphicon-trash"></span>
         </button>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title" id="myModalLabel">Buscar Produtos</h4>
       </div>
       <div class="modal-body">

        <label >Nome Produto</label><br>
         <div class="row">
           <div class="col-lg-12">
             <div class="input-group">
               <input id="nome_produto_pesquisa" name="nome_produto_pesquisa" onkeyup="buscaProduto()" type="text" class="form-control" placeholder="Digite o nome do produto">
               <span class="input-group-btn">
                 <button class="btn btn-success" type="button" onclick="buscaProduto();">Buscar</button>
               </span>
             </div><!-- /input-group -->
           </div><!-- /.col-lg-6 -->
         </div><!-- /.row -->
         <br />

        <table id="table_produto" name="table_produto" class="table table-hover">
           <thead>
             <tr>
               <th>Produto</th>
             </tr>
           </thead>
           <tbody id="tbodyid2">
               <tr>
               </tr>
           </tbody>
         </table>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
       </div>
     </div>
   </div>
  </div>

app/views/vk_anuncios/index.html.erb
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading"><h3 class="panel-title">Listar Anuncios</h3></div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Val. Produto</th>
      <th>Val Com Desconto</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vk_anuncios.each do |vk_anuncio| %>
      <tr>
        <td><%= vk_anuncio.desc_titulo %></td>
        <td><%= vk_anuncio.valr_produto %></td>
        <td><%= vk_anuncio.valr_comdesconto %></td>
        <td><%= vk_anuncio.numr_qtddisponivel %></td>

        <td align='right'>
            <div class="btn-group">
              <%= link_to vk_anuncio, :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-list-alt"></span> Exibir
              <% end %>
              <%= link_to edit_vk_anuncio_path(vk_anuncio), :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-pencil"></span> Editar
              <% end %>
              <%= link_to vk_anuncio, :method => :delete,  :confirm => 'Deseja excluir o registro?', :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-trash"></span> Excluir
              <% end %>
            </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

  <%= link_to new_vk_anuncio_path, :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-file"></span>Novo
  <% end %>

app/views/vk_anuncios/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Novo Anuncio</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

   <%= render 'form' %>

  <%= link_to listaProdutos_path, :class => "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>

app/views/vk_anuncios/produtos.html.erb
<br>
<%= form_tag nil, method: 'GET' do %>
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
        <input id="q" name="q" type="text" class="form-control" placeholder="Digite o nome do produto para pesquisa.">
        <span class="input-group-btn">
          <button class="btn btn-success" type="submit" >Buscar</button>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
  <br />
<% end %>

<div class="panel panel-default">

<!-- Default panel contents -->
<div class="panel-heading"><h3 class="panel-title">Selecione um produto para anunciar</h3></div>

<table class="table table-hover">  <thead>

  </thead>
  <tbody>
    <% @vk_produtos.each do |vk_produto| %>
      <tr>
        <td><%= vk_produto.nome_produto %></td>
        <td align='right'>
            <div class="btn-group">
              <%= link_to show_produto_vk_anuncio_path(vk_produto), :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-list-alt"></span> Visualizar
              <% end %>
              <%= link_to anunciar_path(vk_produto), :class => "btn btn-default btn-sm" do %> Anunciar
                <span class="glyphicon glyphicon-chevron-right"></span>
              <% end %>
            </div>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="row">
 <div class="col-lg-12">
    <%= will_paginate @vk_produtos, renderer: BootstrapPagination::Rails, :inner_window => 1, :outer_window => 0, class: "paginates"  %>
 </div>
</div>

app/views/vk_anuncios/show.html.erb
<%if notice %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     <%= notice %>
</div>
<%end%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Anuncio</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

<p>
  <strong>Titulo Anuncio:</strong>
  <%= @vk_anuncio.desc_titulo %>
</p>

<p>
  <strong>Descrição Anuncio:</strong>
  <%= @vk_anuncio.desc_anuncio %>
</p>
<div class="row">
 <div class="col-lg-3" >
    <p>
      <strong>Valor Produto:</strong>
      <%= @vk_anuncio.valr_produto %>
    </p>
 </div>
 <div class="col-lg-3" >
    <p>
      <strong>Valor Com Desconto:</strong>
      <%= @vk_anuncio.valr_comdesconto %>
    </p>
 </div>
 <div class="col-lg-3" >
    <p>
      <strong>Data inicio:</strong>
      <%= @vk_anuncio.data_inicio.blank? ? '' : @vk_anuncio.data_inicio.strftime("%d/%m/%Y")%>
    </p>
</div>
 <div class="col-lg-3" >
    <p>
      <strong>Data fim:</strong>
      <%= @vk_anuncio.data_fim.blank? ? '' : @vk_anuncio.data_fim.strftime("%d/%m/%Y") %>
    </p>
 </div>
</div>

<p>
  <strong>Produto:</strong>
  <%= @vk_anuncio.vk_produto.nome_produto %>
</p>
<hr>
<div class="row mar-bot40">
  <ul>
    <%for fotoproduto in @vk_anuncio.vk_produto.vk_fotoproduto %>
    <div class="col-lg-3" >
      <li><%= link_to image_tag(fotoproduto.image.url(:thumb))%></li>
    </div>
    <%end%>
  </ul>
  <div class="col-lg-7">
    <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        Cadastre todos os endereços das lojas onde essa promoção estará disponivel.
   </div>
  </div>
</div>
<hr>

<button class="btn btn-success" type="button" onclick="$('#myModal1').modal('show');">Adicionar Endereços
   <span  class="glyphicon glyphicon-plus-sign"></span>
</button>
<hr>

<table class="table table-hover">
    <thead>
      <tr>
        <th>Rua</th>
        <th>Quadra</th>
        <th>Lote</th>
        <th>Bairro</th>
        <th>Cep</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th></th>
      </tr>
    </thead>
    <tbody id="tlbendereco">
      <% @vk_enderecoAnuncio.each do |anuncio| %>
        <tr>
          <td><%= anuncio.vk_endereco.nome_rua %></td>
          <td><%= anuncio.vk_endereco.desc_quadra %></td>
          <td><%= anuncio.vk_endereco.desc_lote %></td>
          <td><%= anuncio.vk_endereco.nome_bairro %></td>
           <td><%= anuncio.vk_endereco.desc_cep %></td>
          <td><%= anuncio.vk_endereco.vk_cidade.nome_cidade %></td>
          <td><%= anuncio.vk_endereco.vk_cidade.vk_estado.sigl_estado %></td>
          <td align='right'>

          <button class="btn btn-default btn-sm" type="button" onclick="exclui_endereco('<%=anuncio.id%>');">
              <span  class="glyphicon glyphicon-trash"></span>
         </button>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>

<div class="btn-group">
<%= link_to edit_vk_anuncio_path(@vk_anuncio), :class => "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-pencil"></span> Editar
<% end %>
<%= link_to vk_anuncios_path, :class => "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-arrow-left"></span> Voltar
<% end %>
</div>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
       <h4 class="modal-title" id="myModalLabel">Lista de Endereços</h4>
     </div>
     <div class="modal-body">
       <br />

      <table id="table_produto" name="table_produto" class="table table-hover">
         <thead>
           <tr>
           </tr>
         </thead>
         <tbody id="tbodyid2">
             <tr>
             </tr>
         </tbody>
       </table>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
     </div>
   </div>
 </div>
</div>


<script>

function salva_endereco(vk_endereco_id){
      $.ajax({
        url: '<%= salvaEnderecoAnuncio_path %>',
        data : {
          vk_anuncio_id : '<%=@vk_anuncio.id%>',
          vk_endereco_id :vk_endereco_id
        },
        success: function(data){
          $('#tlbendereco').empty();
          for (var i in data) {
            var item = data[i];
             $('#tlbendereco').append('<tr><td>'+item.nome_rua+'</td><td>'+item.desc_quadra+'</td><td>'+item.desc_lote+'</td><td>'+item.nome_bairro+'</td><td>'+item.desc_cep+'</td><td>'+item.nome_cidade+'</td><td>'+item.sigl_estado+'</td><td align="right"><button class="btn btn-default btn-sm" type="button" onclick="AcaoExcluir('+item.id+');"><span  class="glyphicon glyphicon-trash"></span></button><td/>')
          };
        }
      })
    }

    function busca_endereco(){
          $.ajax({
            url: '<%= buscaEnderecoEmpresa_path %>',
            data : {
              vk_empresa_id : '<%=current_user.vk_empresa_id%>'
            },
            success: function(data){
              $('#tbodyid2').empty();
              for (var i in data) {
                var item = data[i];
                 $('#tbodyid2').append('<tr><td>Rua:'+item.nome_rua+' Qd.'+item.desc_quadra+' Lt.'+item.desc_lote+' '+item.nome_bairro+' '+item.nome_cidade+'-'+item.sigl_estado+'</td><td align="right"><button class="btn btn-default btn-sm" type="button" onclick="salva_endereco('+item.vk_endereco_id+');"><span  class="glyphicon glyphicon-floppy-save"></span></button><td/></tr>')
              };
            }
          })
      }


  function exclui_endereco(id){
            $.ajax({
              url: '<%= excluiEnderecoAnuncio_path %>',
              data : {
                vk_anuncio_id : '<%=@vk_anuncio.id%>',
                id :id
              },
              success: function(data){
                $('#tlbendereco').empty();
                for (var i in data) {
                  var item = data[i];
                   $('#tlbendereco').append('<tr><td>'+item.nome_rua+'</td><td>'+item.desc_quadra+'</td><td>'+item.desc_lote+'</td><td>'+item.nome_bairro+'</td><td>'+item.desc_cep+'</td><td>'+item.nome_cidade+'</td><td>'+item.sigl_estado+'</td><td align="right"><button class="btn btn-default btn-sm" type="button" onclick="exclui_endereco('+item.id+');"><span  class="glyphicon glyphicon-trash"></span></button><td/>')
                };
              }
        })
    }

  busca_endereco();

</script>