config/routes.rb
Rails.application.routes.draw do

  resources :vk_enderecoanuncios
  resources :vk_enderecoempresas
  resources :vk_anunciofavoritos
  resources :vk_anuncios do
    member do
      get  :endereco
      get  :show_produto
    end
  end
  resources :vk_empresavitrines
  resources :vk_vitrines
  resources :vk_produtos
  resources :vk_empresas
  resources :vk_enderecos
  resources :vk_categoriaprodutos
  devise_for :users
  resources :vk_cidades
  resources :vk_estados

  root  'site#home'

  match '/listarCidade', to: 'vk_cidades#get_cities', via: 'get'
  match '/buscaVitrines', to: 'vk_vitrines#buscaVitrines', via: 'get'

  get '/anuncioshow/:id', to: 'site#show_anuncio', as: 'anuncioshow'
  get '/olhekpesquisa', to: 'site#index', as: 'olhekpesquisa'

  match '/buscaProdutos', to: 'vk_produtos#busca_produtos', via: 'get'

  match '/olheksalvarFavorito', to: 'vk_anunciofavoritos#salvar', via: 'get'
  match '/recomendar', to: 'vk_anuncios#recomendar', via: 'get'

  match '/olheksalvaEndereco', to: 'vk_empresas#salva_endereco', via: 'get'
  match '/olhekexcluiEndereco', to: 'vk_empresas#exclui_endereco', via: 'get'

  match '/listaProdutos', to: 'vk_anuncios#produtos', via: 'get'

  get '/anunciar/:produto_id', to: 'vk_anuncios#new', as: 'anunciar'
  get '/buscaEnderecoEmpresa', to: 'vk_anuncios#busca_endereco_empresa', as: 'buscaEnderecoEmpresa'
  get '/buscaEnderecoAnuncio', to: 'vk_anuncios#busca_endereco_anuncio', as: 'buscaEnderecoAnuncio'
  get '/salvaEnderecoAnuncio', to: 'vk_anuncios#salva_endereco_anuncio', as: 'salvaEnderecoAnuncio'
  get '/excluiEnderecoAnuncio', to: 'vk_anuncios#exclui_endereco_anuncio', as: 'excluiEnderecoAnuncio'
  get '/:id', to: 'site#show_empresa', as: 'loja'










end

app/models/vk_endereco.rb
class VkEndereco < ActiveRecord::Base
  belongs_to :vk_cidade
end

app/controllers/vk_enderecos_controller.rb
class VkEnderecosController < ApplicationController
  before_action :set_vk_endereco, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vk_enderecos = VkEndereco.all
    respond_with(@vk_enderecos)
  end

  def show
    respond_with(@vk_endereco)
  end

  def new
    @vk_endereco = VkEndereco.new
    respond_with(@vk_endereco)
  end

  def edit
  end

  def create
    @vk_endereco = VkEndereco.new(vk_endereco_params)
    @vk_endereco.save
    respond_with(@vk_endereco)
  end

  def update
    @vk_endereco.update(vk_endereco_params)
    respond_with(@vk_endereco)
  end

  def destroy
    @vk_endereco.destroy
    respond_with(@vk_endereco)
  end

  private
    def set_vk_endereco
      @vk_endereco = VkEndereco.find(params[:id])
    end

    def vk_endereco_params
      params.require(:vk_endereco).permit(:nome_bairro, :nome_rua, :desc_quadra, :desc_lote, :desc_complemento, :desc_cep, :vk_cidade_id, :latitude, :longitude)
    end
end

app/helpers/vk_enderecos_helper.rb
module VkEnderecosHelper
end

app/views/vk_enderecos/_form.html.erb
<%= form_for(@vk_endereco) do |f| %>
  <% if @vk_endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vk_endereco.errors.count, "error") %> prohibited this vk_endereco from being saved:</h2>

      <ul>
      <% @vk_endereco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_bairro %><br>
    <%= f.text_field :nome_bairro %>
  </div>
  <div class="field">
    <%= f.label :nome_rua %><br>
    <%= f.text_field :nome_rua %>
  </div>
  <div class="field">
    <%= f.label :desc_quadra %><br>
    <%= f.text_field :desc_quadra %>
  </div>
  <div class="field">
    <%= f.label :desc_lote %><br>
    <%= f.text_field :desc_lote %>
  </div>
  <div class="field">
    <%= f.label :desc_complemento %><br>
    <%= f.text_field :desc_complemento %>
  </div>
  <div class="field">
    <%= f.label :desc_cep %><br>
    <%= f.text_field :desc_cep %>
  </div>
  <div class="field">
    <%= f.label :vk_cidade_id %><br>
    <%= f.text_field :vk_cidade_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vk_enderecos/edit.html.erb
<h1>Editing vk_endereco</h1>

<%= render 'form' %>

<%= link_to 'Show', @vk_endereco %> |
<%= link_to 'Back', vk_enderecos_path %>

app/views/vk_enderecos/index.html.erb
<h1>Listing vk_enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Nome bairro</th>
      <th>Nome rua</th>
      <th>Desc quadra</th>
      <th>Desc lote</th>
      <th>Desc complemento</th>
      <th>Desc cep</th>
      <th>Vk cidade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vk_enderecos.each do |vk_endereco| %>
      <tr>
        <td><%= vk_endereco.nome_bairro %></td>
        <td><%= vk_endereco.nome_rua %></td>
        <td><%= vk_endereco.desc_quadra %></td>
        <td><%= vk_endereco.desc_lote %></td>
        <td><%= vk_endereco.desc_complemento %></td>
        <td><%= vk_endereco.desc_cep %></td>
        <td><%= vk_endereco.vk_cidade %></td>
        <td><%= link_to 'Show', vk_endereco %></td>
        <td><%= link_to 'Edit', edit_vk_endereco_path(vk_endereco) %></td>
        <td><%= link_to 'Destroy', vk_endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vk endereco', new_vk_endereco_path %>

app/views/vk_enderecos/new.html.erb
<h1>New vk_endereco</h1>

<%= render 'form' %>

<%= link_to 'Back', vk_enderecos_path %>

app/views/vk_enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome bairro:</strong>
  <%= @vk_endereco.nome_bairro %>
</p>

<p>
  <strong>Nome rua:</strong>
  <%= @vk_endereco.nome_rua %>
</p>

<p>
  <strong>Desc quadra:</strong>
  <%= @vk_endereco.desc_quadra %>
</p>

<p>
  <strong>Desc lote:</strong>
  <%= @vk_endereco.desc_lote %>
</p>

<p>
  <strong>Desc complemento:</strong>
  <%= @vk_endereco.desc_complemento %>
</p>

<p>
  <strong>Desc cep:</strong>
  <%= @vk_endereco.desc_cep %>
</p>

<p>
  <strong>Vk cidade:</strong>
  <%= @vk_endereco.vk_cidade %>
</p>

<%= link_to 'Edit', edit_vk_endereco_path(@vk_endereco) %> |
<%= link_to 'Back', vk_enderecos_path %>